export const ROUTES = {
  login: "/auth/login",
  googleLogin: "/auth/google",
  register: "/auth/register",
  forgotPassword: "/auth/forgot-password",
  resetPassword: "/auth/reset-password",
  verify: "/auth/verify",
  dashboard: "/overview",
  transaction: "/transaction",
  transactionList: "/transaction/list",
  account: "/account",
  accountList: "/account/list",
  investment: "/investment",
  creditCard: "/credit-card",
  creditCardList: "/credit-card/list",
  loan: "/loan",
  service: "/service",
  privilege: "/privilege",
  setting: "/setting",
  profileSetting: "/setting/profile",
};
